### ISSUE TITLE
Error When Compiling

### ISSUE THREAD

**Issue by enkianu** [NYAN-x-CAT/AsyncRAT-C-Sharp#11]
![112](https://user-images.githubusercontent.com/38964662/57586370-e4b9da80-74ec-11e9-91eb-171f383a71fe.png)

I get that error when compiling. 

By the way, solid work...kudos

**Comment by NYAN-x-CAT** [comment]
I'm not familiar with this error. but I coded this RAT using VS 2019. maybe you should update your VS.

**Comment by enkianu** [comment]
Yeah that's 2019....the latest update

**Comment by enkianu** [comment]
I'll try a fix...if it's done, I'll update here for others.

**Comment by enkianu** [comment]
I simply closed VS, deleted the ".vs" folder and re-opened the solution and re-compiled.  Just like that........
I can't say what caused the earlier error but it's working like a charm now!
