### ISSUE TITLE
Same stub and settings works in windows10 but windows 7

### ISSUE THREAD

**Issue by Abraham313** [NYAN-x-CAT/AsyncRAT-C-Sharp#122]
I have tested your last released - AsyncRAT v0.5.4H and pre-released  version (AsyncRAT 0.5.4J).But, pre-released version works both of windows 10 and 7 see this http://prntscr.com/pjhr0x .I have tested this on default windows10 and in windows 7 with installed Microsoft .NET Framework 4 (Standalone Installer) version.It was no problem.

But your latest released version doesn't report to the panel.Please,see this http://prntscr.com/pjha7v  I have tested it on windows 7 with installed Microsoft .NET Framework 4 (Standalone Installer) version, dotnet 4.6 version and 4.8 versions individually.But none of them report to my panel but same stub with same settings  for windows 10 report my panel..
Would you checked this please ?
thanks

**Comment by NYAN-x-CAT** [comment]
Please open the old version and update all clients with the new H version.

**Comment by Abraham313** [comment]
Sorry to say that it still doesn't work in windows 7  after stub update H version but windows 8.1 and  10 are ok.I tested windows 7 with Lime Rat for more sure but Lime Rat works fine

**Comment by NYAN-x-CAT** [comment]
This software is and was developed using windows 7. You need to provide more details.

**Comment by Abraham313** [comment]
Brother!
I have made 2 videos for this.I am not going to post the videos link is in here for my IP.Because,I have not edited the videos.I have send you email into your ( NYANxCAT@protonmail.com ) mail. The mail title was " Bugs of AsyncRAT v0.5.4H Rat". Please,Check it.
kind regards
