### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by 0x00chad** [NYAN-x-CAT/AsyncRAT-C-Sharp#13]
The program works great but i was missing something like Offline keylogger, i can send command in cmd in clients, and enable disable critical process in builder.,

**Comment by Archikle** [comment]
0x00chad, I don't think you understand the purpose of this program. This is not supposed to be a good RAT, and that's why it isn't. It's something called a "Loader", its main purpose is to "load" malware onto the machines.
