### ISSUE TITLE
0.5.6 Clients not showing up

### ISSUE THREAD

**Issue by imnezaki** [NYAN-x-CAT/AsyncRAT-C-Sharp#146]
Hi, 
When i run version 5.6 i see data transfere, but no clients showing up in the list.
If i run the the rat on my computer it shows on the list. But when i run it on other computer it dosen't show on clients list, i just see the sent and received bytes changing..
Tried multiple ports, same issue.
I opened ports and set them up in router and firewall, also tried to disable firewall but still nothing happens. But version 0.5.3 is working for me.

Is there something wrong?

**Comment by NYAN-x-CAT** [comment]
The clients are using 0.5.6 stub? or 5.3 and below?

**Comment by imnezaki** [comment]
nah no previous versions i just wanted to try the new 0.5.6 release, i built new stub using 0.5.6 and tried to run it on other computer it didn't show up on my clients list, however if i run it on my computer it shows i tried to use pastbin aswell.
looks like only version 0.5.3 is working for me.

**Comment by NYAN-x-CAT** [comment]
"on another computer" which windows version?

**Comment by NYAN-x-CAT** [comment]
If you don't mind, give me discord so we can share teamviewer, I can fix it faster this way.

**Comment by imnezaki** [comment]
Sure 
Nezaki#3927

**Comment by NYAN-x-CAT** [comment]
Fixed. Thanks bro.
