### ISSUE TITLE
Client not detecting

### ISSUE THREAD

**Issue by 93493** [NYAN-x-CAT/AsyncRAT-C-Sharp#165]
Hello,

tried Async but it doesn't connects. In a Virtual Machine it works. Tried also LimeRat, the same. Ports are closed there. AV etc is deactivated. Help?

Edit: I meant client not connecting in the main title.

**Comment by 93493** [comment]
HELLO??

**Comment by NYAN-x-CAT** [comment]
Do you feel that your issue is actually a bug? All I see is someone is asking for technical help.
