### ISSUE TITLE
Remote shell in limerat

### ISSUE THREAD

**Issue by 0x00chad** [NYAN-x-CAT/AsyncRAT-C-Sharp#19]
Please add remote shell in Limerat and please fix remote desktop i think it is scale in 70% sorry not issue in AsyncRat i cant add issue in limerat, thanks,

**Comment by 0x00chad** [comment]
and please add enable and disable critical process in builder in limerat i have some issue in critical process in laptop when i charge laptop and remove charger it cause BSOD,

**Comment by NYAN-x-CAT** [comment]
Please, @0x00chad don't post anything that isn't about AsyncRAT.
LR is a dead project and I won't update it. you are welcome to download the source code and add any feature you want.
