### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by Thoxy67** [NYAN-x-CAT/AsyncRAT-C-Sharp#26]
I wrote a library to retrieve passwords stored in several browsers to return a string.

If you want to be inspired by it, modify it, or integrate it here is the link : [stealerlib](https://gitlab.com/thoxy/stealerlib)

I will make update sometimes to add somes other browsers and services.

**Comment by NYAN-x-CAT** [comment]
excellent job! I will integrate it when you finish it. But I faced a problem, it won't load if the DLL it's a 4.5+ dependency. I would love to hear feedback from you.

The good thing here that there is no need to update the client to recover new passwords, Just compile the server with the new DLL.

Keep me updated @Thoxy67

**Comment by Thoxy67** [comment]
Thank you for your interest in me @NYAN-x-CAT

I downgraded the version of .net to 4.5 I even think that downgrading to 4.0 should work too.

I added a few minutes ago a function for Cookies on Firefox and worked on Chromium derivatives to reduce the number of files.

I thought it would be a good idea to integrate some kind of directory to load plugins, so I don't have too many ideas about how to do it, but just to make it easier for people who have plugin ideas or private things (Like Private Ⓔⓧⓟⓛⓞⓘⓣ).
If you know how to integrate it would be an idea (Example in a new tab make a plugins menu or dynamically in the contextmenu add compatible plugins in a menu)

**Comment by NYAN-x-CAT** [comment]
I thought about this idea a few months ago. I saw it on many RATs. But I have never seen anyone sharing any kind of public or private plugin. That's why I didn't do it.
the "stealerlib" is a great share. I will add it and please keep me updated.

**Comment by arsium** [comment]
I really would like to know how did you release a library like that thoxy ?
