### ISSUE TITLE
Password Recovery Error

### ISSUE THREAD

**Issue by 0x00chad** [NYAN-x-CAT/AsyncRAT-C-Sharp#35]
Error Occured when i try to click Password Recovery

**Comment by 0x00chad** [comment]
Error: Client 127.0.0.1 error: Exception has been thrown by the target of an invocation

the error can be seen in logs.

**Comment by enkianu** [comment]
> Error: Client 127.0.0.1 error: Exception has been thrown by the target of an invocation
> 
> the error can be seen in logs.

Can't seem to reproduce the error. Works fine with me.

**Comment by NYAN-x-CAT** [comment]
Great that I updated the log to show errors. I guess you need to install framework 4.5 or the recovery won't work. Maybe in the feature @Thoxy67  will fix it.

**Comment by 0x00chad** [comment]
ok thanks., and by the way thanks for adding critical process in builder.,

**Comment by 0x00chad** [comment]
you have plan adding mouse and keyboard control on remote desktop?

**Comment by NYAN-x-CAT** [comment]
@0x00chad Maybe in the next update.
