### ISSUE TITLE
Lost all client with v0.4.9C

### ISSUE THREAD

**Issue by Trustdee** [NYAN-x-CAT/AsyncRAT-C-Sharp#37]
I tried updating all client with v0.4.9C and lost all client  ,  Stub Refused to run  : 

Please take a look and fix

**Comment by NYAN-x-CAT** [comment]
There is nothing wrong with the stub. I need more details. Tell me what you did.

**Comment by Trustdee** [comment]
Am using the latest release from you **v0.4.9C** ,  and there is a version number difference.  Maybe i will go down and wait for next release  

![image](https://user-images.githubusercontent.com/17923943/58170730-305a4a00-7c8c-11e9-9d32-38a79aa088b4.png)

**Comment by NYAN-x-CAT** [comment]
This is another topic. I will fix this simple mistake right now. This should not affect the RAT performance.

**Comment by NYAN-x-CAT** [comment]
Fixed. and I updated the compiled version. Thank you.
