### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by 0x00chad** [NYAN-x-CAT/AsyncRAT-C-Sharp#40]
Maybe it good to have Clients data/folder in Server (shorcut to clients folder on right click) it hard to search data and find it ID in clients folder.

**Comment by NYAN-x-CAT** [comment]
Yes, it's a good suggestion. Thank you @0x00chad . I will add it

**Comment by NYAN-x-CAT** [comment]
I added it. Also, I updated the compiled version.
