### ISSUE TITLE
USB Spread

### ISSUE THREAD

**Issue by 0x00chad** [NYAN-x-CAT/AsyncRAT-C-Sharp#43]
Enable/Disable USB Spread in server and show it in dashboard if the client has USB Spread enable or not. Because i dont know how to stop the spread after i click the USB Spread button.

**Comment by enkianu** [comment]
Just as in LimeRAT i suppose.

**Comment by 0x00chad** [comment]
Yes, but i never use USB spread in limerat i dont know if i can enable or disable spread there,

**Comment by NYAN-x-CAT** [comment]
Hi. 
It will run just once per click. There is no need to disable\enable.
