### ISSUE TITLE
Show folder not working

### ISSUE THREAD

**Issue by 0x00chad** [NYAN-x-CAT/AsyncRAT-C-Sharp#44]
The Show folder is not  working in Windows 7.

**Comment by 0x00chad** [comment]
Oh its now working. i think the client dont have folder in clients folder thats why its not working earlier. 
The password is not spelled correct Passowrds.txt.

**Comment by NYAN-x-CAT** [comment]
If the folder is empty it won't work.
I will correct the password. Thanks

**Comment by 0x00chad** [comment]
maybe its good to auto generate folder on clicking show folder so that the user wont think it not working when they click, just a suggestion,

**Comment by 0x00chad** [comment]
and the format in the password maybe its good to have newline after the address , username and password.
