### ISSUE TITLE
Theme Help

### ISSUE THREAD

**Issue by 0x00chad** [NYAN-x-CAT/AsyncRAT-C-Sharp#50]
im a changing the theme but i have a problem how can i make it white the encircled blue.
i cant upload image here. i dont know why.

https://ibb.co/tH5GHXy

**Comment by NYAN-x-CAT** [comment]
Nice theme. Does this happen when you resize the form?

**Comment by 0x00chad** [comment]
i think the has limit in only notification i dont know how to expand the white even if i change it to use the white theme,

**Comment by NYAN-x-CAT** [comment]
Try to remove the spaces in the notification text. Try to change spring value to true.
I really can't help you because I'm not using this theme.

**Comment by Archikle** [comment]
It's decent, you could have done better imo

MetroFramework is REALLY commonly used.
