### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by 0x00chad** [NYAN-x-CAT/AsyncRAT-C-Sharp#52]
can i use two, like pastebin and the other one i use ghostbin for backup?

**Comment by NYAN-x-CAT** [comment]
There is no reason for this method. 
Also, Ghostbin will be shutting down in May 2019.
You may use https://gist.github.com/ but I didn't test it yet.

**Comment by enkianu** [comment]
> There is no reason for this method.
> Also, Ghostbin will be shutting down in May 2019.
> You may use https://gist.github.com/ but I didn't test it yet.

Whenever i use gisthub's text host, i get random US clients show up immediately on my server. Seems to me like bots

**Comment by NYAN-x-CAT** [comment]
It's a honeypot. and it's not from GitHub.
