### ISSUE TITLE
Error On compile - MsBuildMajorVersion

### ISSUE THREAD

**Issue by 0x00chad** [NYAN-x-CAT/AsyncRAT-C-Sharp#61]
A numeric comparison was attempted on "$(MsBuildMajorVersion)" that evaluates to "" instead of number, in condition $(MsBuildMajorVersion) < 16) And $ (OS) =='Windows_NT".

**Comment by NYAN-x-CAT** [comment]
Close visual studio and open it again.

**Comment by 0x00chad** [comment]
tnx

**Comment by kokabi1365** [comment]
> Close visual studio and open it again.

Restarting, almost always does miracles in Microsoft products!
