### ISSUE TITLE
Help Needed with StealerLib DLL

### ISSUE THREAD

**Issue by enkianu** [NYAN-x-CAT/AsyncRAT-C-Sharp#77]
Hi folks,

Been playing with the source files and i've had this persistent problem of being unable to downgrade the .NET version of the StealerLIB from 4.5 to 4.0. I'm always faced with problem of **System.Net.Http** reference not resolving despite restoring nuget packages. It only seems to work when compiled with 4.5 framework which gives an exception error when run against windows7 systems. I'll appreciate your help and enlightenment.

![Annotation 2019-06-25 113113](https://user-images.githubusercontent.com/38964662/60112809-82383900-973e-11e9-8bf6-0594a407abed.png)
![Annotation 2019-06-25 112733](https://user-images.githubusercontent.com/38964662/60112810-82d0cf80-973e-11e9-875a-28d8f9a4cbb4.png)
![Annotation 2019-06-25 112654](https://user-images.githubusercontent.com/38964662/60112812-83696600-973e-11e9-8e27-fc4e1bfbe3a4.png)

**Comment by NYAN-x-CAT** [comment]
My plugin. https://ufile.io/7gil6pup

**Comment by enkianu** [comment]
> My plugin. https://ufile.io/7gil6pup

Thanks Nyan Cat. I noticed that this runs on framework 4.5+ and i still get the **System.Net.Http** error even without modification. What could be the issue? 

And I was hoping to make it run on a 4.0 framework. 

![Annotation 2019-06-25 123901](https://user-images.githubusercontent.com/38964662/60118109-946ba480-9749-11e9-99fe-bae97103a8cb.png)

**Comment by NYAN-x-CAT** [comment]
You can ignore warnings. you can also delete system.net.http.

**Comment by enkianu** [comment]
> You can ignore warnings. you can also delete system.net.http.

Oh thanks for that. I've been tempted to delete that fuc*er and just compile. Your latest release is superb as always
