### ISSUE TITLE
[REQ FEATURE] Lower .Net Dependency

### ISSUE THREAD

**Issue by b7001** [NYAN-x-CAT/AsyncRAT-C-Sharp#79]
Hello @NYAN-x-CAT, love the work.

It is possible to have the stub/client a lower .net dependency? Say 3.5.1 ?

I have been pen testing systems using your RAT. However finding this painful due to the dependencies of .Net 4.0. 
I know Win10 supports .net4 by default, but if the target was an earlier system it makes the RAT less reliable.

**Comment by UsrTkn** [comment]
Didnt read stub source, but maybe few features need 4.0 framework, however you can use nyan's vbs downloader and check for 3.5 or 4.0 then download what u want

**Comment by NYAN-x-CAT** [comment]
@b7001 
You can always lower it to 2.0 or 3.5 but you need to do some changes. the project will remain at 4.0 so you will have to change everything on every update.

@UsrTkn I updated the script. it's FUD and fileless.
