### ISSUE TITLE
Socket

### ISSUE THREAD

**Issue by Archikle** [NYAN-x-CAT/AsyncRAT-C-Sharp#8]
I have seven incoming connections. They will not work, when I run a simple listening tool, the connections come in and are logged. On Async, they are not logged as connections nor is the port open on canyouseeme.org.

**Comment by NYAN-x-CAT** [comment]
Hi. Can you please explain more? Are you using this port on another rats?

**Comment by Archikle** [comment]
Its not a problem anymore, I just had to disable Avast and windows defender firewall.

**Comment by NYAN-x-CAT** [comment]
I see, a honeypot.
