### ISSUE TITLE
{File Manager} Overwrites a different file with same name.

### ISSUE THREAD

**Issue by enkianu** [NYAN-x-CAT/AsyncRAT-C-Sharp#80]
Hi folks,

So i noticed that files with same names are overwritten while downoading via the filemanager. Even if such files are sourced from a completely different folder or drives and even if they've got different content. I think it would be great to have RAT automatically rename the most recent file by appending a number or timestamp.

**Comment by NYAN-x-CAT** [comment]
You are right. I will fix this issue. Thanks!

**Comment by enkianu** [comment]
Great.
