### ISSUE TITLE
Rat closes by it self

### ISSUE THREAD

**Issue by araphat1111** [NYAN-x-CAT/AsyncRAT-C-Sharp#83]
please when i open this rat, the panel will open but within 2 minutes.
can you explain how i can fic this?

**Comment by NYAN-x-CAT** [comment]
Hi. Good morning.

This is not how to ask for help. you need to add more information.

Also since the RAT is working for everybody, then this issue is within your PC system. You need an IT helpdesk guy, not coders.

**Comment by araphat1111** [comment]
i need to chat you in private if you don't mind.
skype or jabber
