### ISSUE TITLE
Mutex system

### ISSUE THREAD

**Issue by Archikle** [NYAN-x-CAT/AsyncRAT-C-Sharp#9]
Still trying to test async and how well it works, flawless except for one thing. Please stop blocking IP's! I lost all but one client because the rest disconnected and reconnected, but they "tried to connect with the wrong password", ironic considering that there is no option to set a password in the builder lol (I understand that the password you choose at the beginning is *probably* the password for building the client).

**Comment by UsrTkn** [comment]
The password you choose when you open the RAT, is used when you build new Client.exe
if you have Clients with different password you must use 2 diferent rats (for now until nyans update?)
What nyan can do is add a new options tabpage with port listen, passwords, and stuff

**Comment by NYAN-x-CAT** [comment]
Fixed.
