### ISSUE TITLE
[Suggestion] Crypto Miner, VPN and Two-way audio

### ISSUE THREAD

**Issue by Saku241** [NYAN-x-CAT/AsyncRAT-C-Sharp#90]
Great tool, I have some suggestions
Nothing to hurry

It would be great to add a crypto minor, a VPN to use IP from clients and a two way audio system

**Comment by Archikle** [comment]
VPN is called Reverse Proxy, and people are currently figuring it out. Crypto Miner can be implemented but I don't think its a top priority. Two-way audio sounds cool but I don't see the use for it.
